create table people (
  id int generated by default as identity,
  name varchar not null,

  primary key (id)
);

create table accounts (
    id int generated by default as identity,
    balance decimal not null,
    owner int not null,

    primary key (id),
    foreign key (owner) references people(id)
);
